apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{ .Values.moduleName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.label.moduleLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.label.moduleLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "demo-api.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.targetPort }}
              containerPort: 8989
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
